version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=LibraryDB;User=sa;Password=Heslo1234.;Trusted_Connection=False;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "80:80"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Heslo1234."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
networks:
  mynetwork:
    driver: bridge